/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/

#ifndef QML_HYDRA_PLUGIN_H
#define QML_HYDRA_PLUGIN_H

#include <QQmlExtensionPlugin>
#include <qqml.h>

class QmlHydra;
class QmlHydraAttached;
class QmlHydraPost;
class QmlHydraPostAttached;
class QmlHydraLedger;
class QmlHydraLedgerAttached;

#include "QmlHydra.h"
#include "QmlHydraPost.h"
#include "QmlHydraLedger.h"

class QmlHydraPlugin : public QQmlExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA (IID "org.qt-project.Qt.QQmlExtensionInterface")
    
public:
    void registerTypes (const char *uri)
    {
        qmlRegisterType<QmlHydra> (uri, 1, 0, "QmlHydra");
        qmlRegisterType<QmlHydraAttached>();
        qmlRegisterType<QmlHydraPost> (uri, 1, 0, "QmlHydraPost");
        qmlRegisterType<QmlHydraPostAttached>();
        qmlRegisterType<QmlHydraLedger> (uri, 1, 0, "QmlHydraLedger");
        qmlRegisterType<QmlHydraLedgerAttached>();
    };
};

#endif

/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
