################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################

require 'ffi'

require_relative 'ffi/version'


module Hydra
  module FFI
    extend ::FFI::Library
    
    def self.available?
      @available
    end
    
    begin
      lib_name = 'libhydra'
      lib_paths = ['/usr/local/lib', '/opt/local/lib', '/usr/lib64']
        .map { |path| "#{path}/#{lib_name}.#{::FFI::Platform::LIBSUFFIX}" }
      ffi_lib lib_paths + [lib_name]
      @available = true
    rescue LoadError
      warn ""
      warn "WARNING: ::Hydra::FFI is not available without libhydra."
      warn ""
      @available = false
    end
    
    if available?
      opts = {
        blocking: true  # only necessary on MRI to deal with the GIL.
      }
      
      attach_function :hydra_new, [:string], :pointer, **opts
      attach_function :hydra_destroy, [:pointer], :void, **opts
      attach_function :hydra_set_nickname, [:pointer, :string], :void, **opts
      attach_function :hydra_nickname, [:pointer], :string, **opts
      attach_function :hydra_set_animate, [:pointer], :void, **opts
      attach_function :hydra_set_verbose, [:pointer], :void, **opts
      attach_function :hydra_set_local_ipc, [:pointer], :void, **opts
      attach_function :hydra_start, [:pointer], :int, **opts
      attach_function :hydra_fetch, [:pointer], :pointer, **opts
      attach_function :hydra_store_string, [:pointer, :string, :string, :string, :string], :pointer, **opts
      attach_function :hydra_store_file, [:pointer, :string, :string, :string, :string], :pointer, **opts
      attach_function :hydra_store_chunk, [:pointer, :string, :string, :string, :pointer], :pointer, **opts
      attach_function :hydra_version, [:pointer, :pointer, :pointer], :void, **opts
      attach_function :hydra_test, [:bool], :void, **opts
      
      require_relative 'ffi/hydra'
      
      attach_function :hydra_post_new, [:string], :pointer, **opts
      attach_function :hydra_post_destroy, [:pointer], :void, **opts
      attach_function :hydra_post_ident, [:pointer], :string, **opts
      attach_function :hydra_post_subject, [:pointer], :string, **opts
      attach_function :hydra_post_timestamp, [:pointer], :string, **opts
      attach_function :hydra_post_parent_id, [:pointer], :string, **opts
      attach_function :hydra_post_mime_type, [:pointer], :string, **opts
      attach_function :hydra_post_digest, [:pointer], :string, **opts
      attach_function :hydra_post_location, [:pointer], :string, **opts
      attach_function :hydra_post_content_size, [:pointer], :pointer, **opts
      attach_function :hydra_post_content, [:pointer], :pointer, **opts
      attach_function :hydra_post_set_parent_id, [:pointer, :string], :void, **opts
      attach_function :hydra_post_set_mime_type, [:pointer, :string], :void, **opts
      attach_function :hydra_post_set_content, [:pointer, :string], :void, **opts
      attach_function :hydra_post_set_data, [:pointer, :pointer, :pointer], :void, **opts
      attach_function :hydra_post_set_file, [:pointer, :string], :int, **opts
      attach_function :hydra_post_save, [:pointer, :string], :int, **opts
      attach_function :hydra_post_load, [:string], :pointer, **opts
      attach_function :hydra_post_fetch, [:pointer, :pointer, :pointer], :pointer, **opts
      attach_function :hydra_post_encode, [:pointer, :pointer], :void, **opts
      attach_function :hydra_post_decode, [:pointer], :pointer, **opts
      attach_function :hydra_post_dup, [:pointer], :pointer, **opts
      attach_function :hydra_post_print, [:pointer], :void, **opts
      attach_function :hydra_post_test, [:bool], :void, **opts
      
      require_relative 'ffi/post'
    end
  end
end

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
