/*  =========================================================================
    hydra_client - Hydra Client

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of zbroker, the ZeroMQ broker project.           
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

/*
@header
    This is a client for the Hydra protocol.
@discuss
    Generated by zproto and implements a background actor that manages the
    connection to the Hydra server.
@end
*/

#include "hydra_classes.h"

//  Forward reference to method arguments structure
typedef struct _client_args_t client_args_t;

//  This structure defines the context for a client connection
typedef struct {
    //  These properties must always be present in the client_t
    //  and are set by the generated engine. The cmdpipe gets
    //  messages sent to the actor; the msgpipe may be used for
    //  faster asynchronous message flows.
    zsock_t *cmdpipe;           //  Command pipe to/from caller API
    zsock_t *msgpipe;           //  Message pipe to/from caller API
    zsock_t *dealer;            //  Socket to talk to server
    hydra_proto_t *message;     //  Message from and to server
    client_args_t *args;        //  Arguments from methods

    zconfig_t *config;          //  Own configuration data
    char *identity;             //  Own identity to send to server
    char *nickname;             //  Own nickname to send to server
    
    zconfig_t *peer_config;     //  Peer configuration data
    char *oldest;               //  Oldest post we got from peer
    char *newest;               //  Newest post we got from peer
    hydra_post_t *post;         //  Current post we're receiving
    size_t chunk_offset;        //  For fetching post content in chunks
    zsock_t *sink;              //  Where we send posts to be stored
} client_t;

//  Include the generated client engine
#include "hydra_client_engine.inc"

//  Maximum size of chunks we fetch, 1MB seems fair over WiFi
#define CHUNK_SIZE 1024 * 1024 * 10

//  Allocate properties and structures for a new client instance.
//  Return 0 if OK, -1 if failed

static int
client_initialize (client_t *self)
{
    //  Load configuration data
    self->config = zconfig_load ("hydra.cfg");
    assert (self->config);          //  Server must already have started
    self->identity = zconfig_resolve (self->config, "/hydra/identity", NULL);
    assert (self->identity);        //  Server must already have started
    self->nickname = zconfig_resolve (self->config, "/hydra/nickname", "");

    //  Create and connect sink socket; use identity as unique endpoint
    self->sink = zsock_new (ZMQ_PUSH);
    int rc = zsock_connect (self->sink, "inproc://%s", self->identity);
    assert (rc == 0);
    
    return 0;
}

//  Free properties and structures for a client instance

static void
client_terminate (client_t *self)
{
    zconfig_destroy (&self->config);
    zconfig_destroy (&self->peer_config);
    hydra_post_destroy (&self->post);
    zsock_destroy (&self->sink);
    free (self->newest);
    free (self->oldest);
}


//  ---------------------------------------------------------------------------
//  use_connect_timeout
//

static void
use_connect_timeout (client_t *self)
{
    engine_set_timeout (self, self->args->timeout);
}


//  ---------------------------------------------------------------------------
//  connect_to_server_endpoint
//

static void
connect_to_server_endpoint (client_t *self)
{
    if (zsock_connect (self->dealer, "%s", self->args->endpoint)) {
        engine_set_exception (self, bad_endpoint_event);
        zsys_warning ("could not connect to %s", self->args->endpoint);
    }
}


//  ---------------------------------------------------------------------------
//  set_client_identity
//

static void
set_client_identity (client_t *self)
{
    hydra_proto_set_identity (self->message, self->identity);
    hydra_proto_set_nickname (self->message, self->nickname);
}


//  ---------------------------------------------------------------------------
//  use_response_timeout
//

static void
use_response_timeout (client_t *self)
{
    engine_set_timeout (self, 1000);
}


//  ---------------------------------------------------------------------------
//  store_peer_id_and_nickname
//

static void
store_peer_id_and_nickname (client_t *self)
{
    //  Load the peer's config file, or create a new config tree
    self->peer_config = zconfig_loadf ("peers/%s.cfg", hydra_proto_identity (self->message));
    if (!self->peer_config)
        self->peer_config = zconfig_new ("root", NULL);

    //  Store the id and nickname we got from the server
    zconfig_put (self->peer_config, "/peer/identity", hydra_proto_identity (self->message));
    zconfig_put (self->peer_config, "/peer/nickname", hydra_proto_nickname (self->message));
    self->oldest = strdup (zconfig_resolve (self->peer_config, "/peer/oldest", ""));
    self->newest = strdup (zconfig_resolve (self->peer_config, "/peer/newest", ""));
}


//  ---------------------------------------------------------------------------
//  prepare_to_request_status
//

static void
prepare_to_request_status (client_t *self)
{
    hydra_proto_set_oldest (self->message, self->oldest);
    hydra_proto_set_newest (self->message, self->newest);
}


//  ---------------------------------------------------------------------------
//  signal_connected
//

static void
signal_connected (client_t *self)
{
    zsock_send (self->cmdpipe, "si44", "CONNECTED", 0,
                hydra_proto_before (self->message),
                hydra_proto_after (self->message));
}


//  ---------------------------------------------------------------------------
//  save_peer_configuration
//

static void
save_peer_configuration (client_t *self)
{
    //  We store peer configuration data in the "peers" subdirectory
    //  If this doesn't already exist, now is a good time to create it
    zsys_dir_create ("peers");
    zconfig_put (self->peer_config, "/peer/oldest", self->oldest);
    zconfig_put (self->peer_config, "/peer/newest", self->newest);
    char *identity = zconfig_resolve (self->peer_config, "/peer/identity", NULL);
    assert (identity);
    zconfig_savef (self->peer_config, "peers/%s.cfg", identity);
}


//  ---------------------------------------------------------------------------
//  prepare_to_fetch_header
//

static void
prepare_to_fetch_header (client_t *self)
{
    hydra_proto_set_which (self->message, self->args->which);
}


//  ---------------------------------------------------------------------------
//  store_post_metadata
//

static void
store_post_metadata (client_t *self)
{
    hydra_post_destroy (&self->post);
    self->post = hydra_post_decode (self->message);
}


//  ---------------------------------------------------------------------------
//  prepare_to_get_first_chunk
//

static void
prepare_to_get_first_chunk (client_t *self)
{
    //  TODO: stage post data and restart failed transfers
    //  - implement this in hydra_post
    //  - create new post, set_remote
    //  - desired content size, actual content size
    //  - hydra_post tells us what offset & octets to fetch
    //  - hydra_post_store to accept a chunk
    //  - calculate digest on the fly, check it matches at the end
    //  For now, assume 1 post = 1 chunk
    self->chunk_offset = 0;
    hydra_proto_set_offset (self->message, self->chunk_offset);
    hydra_proto_set_octets (self->message, CHUNK_SIZE);
}


//  ---------------------------------------------------------------------------
//  store_post_data_chunk
//

static void
store_post_data_chunk (client_t *self)
{
    //  Only allow one chunk per post for now
    assert (hydra_proto_offset (self->message) == 0);
    zchunk_t *chunk = hydra_proto_content (self->message);
    hydra_post_set_data (self->post, zchunk_data (chunk), zchunk_size (chunk));
}


//  ---------------------------------------------------------------------------
//  prepare_to_get_next_chunk
//

static void
prepare_to_get_next_chunk (client_t *self)
{
    engine_set_exception (self, finished_event);
}


//  ---------------------------------------------------------------------------
//  signal_post_fetched
//

static void
signal_post_fetched (client_t *self)
{
    printf ("FETCHED post=%s\n", hydra_post_ident (self->post));
    zsock_send (self->cmdpipe, "sisssss8", "FETCHED", 0,
        hydra_post_ident (self->post),
        hydra_post_subject (self->post),
        hydra_post_timestamp (self->post),
        hydra_post_parent_id (self->post),
        hydra_post_mime_type (self->post),
        hydra_post_content_size (self->post));
}


//  ---------------------------------------------------------------------------
//  store_the_post_in_ledger
//

static void
store_the_post_in_ledger (client_t *self)
{
    //  Update peer range
    if (self->args->which == HYDRA_PROTO_FETCH_OLDER) {
    printf ("PEER oldest=%s\n", hydra_post_ident (self->post));
        free (self->oldest);
        self->oldest = strdup (hydra_post_ident (self->post));
    }
    else
    if (self->args->which == HYDRA_PROTO_FETCH_NEWER) {
    printf ("PEER newest=%s\n", hydra_post_ident (self->post));
        free (self->newest);
        self->newest = strdup (hydra_post_ident (self->post));
    }
    else
    if (self->args->which == HYDRA_PROTO_FETCH_RESET) {
        free (self->newest);
        free (self->oldest);
        self->newest = strdup ("");
    printf ("PEER newest=- oldest=%s\n", hydra_post_ident (self->post));
        self->oldest = strdup (hydra_post_ident (self->post));
    }
    zsock_send (self->sink, "p", self->post);
    self->post = NULL;
}


//  ---------------------------------------------------------------------------
//  signal_success
//

static void
signal_success (client_t *self)
{
    zsock_send (self->cmdpipe, "si", "SUCCESS", 0);
}


//  ---------------------------------------------------------------------------
//  signal_bad_endpoint
//

static void
signal_bad_endpoint (client_t *self)
{
    zsock_send (self->cmdpipe, "sis", "FAILURE", -1, "Bad server endpoint");
}


//  ---------------------------------------------------------------------------
//  signal_server_not_present
//

static void
signal_server_not_present (client_t *self)
{
    zsock_send (self->cmdpipe, "sis", "FAILURE", -1, "Server is not reachable");
}


//  ---------------------------------------------------------------------------
//  signal_no_data
//

static void
signal_no_data (client_t *self)
{
    zsock_send (self->cmdpipe, "sis", "FAILURE", -1, "No post was found");
}


//  ---------------------------------------------------------------------------
//  signal_post_skipped
//

static void
signal_post_skipped (client_t *self)
{
    zsock_send (self->cmdpipe, "si", "SKIPPED", 0);
}


//  ---------------------------------------------------------------------------
//  signal_unexpected_server_reply
//

static void
signal_unexpected_server_reply (client_t *self)
{
    zsock_send (self->cmdpipe, "sis", "FAILURE", -1, "Unexpected server reply");
}


//  ---------------------------------------------------------------------------
//  signal_incomplete
//

static void
signal_incomplete (client_t *self)
{
    zsock_send (self->cmdpipe, "sis", "FAILURE", -1, "Premature disconnection");
}


//  ---------------------------------------------------------------------------
//  signal_internal_error
//

static void
signal_internal_error (client_t *self)
{
    zsock_send (self->cmdpipe, "sis", "FAILURE", -1, "Internal server error");
}


//  ---------------------------------------------------------------------------
//  Selftest

void
hydra_client_test (bool verbose)
{
    printf (" * hydra_client: ");
    if (verbose)
        printf ("\n");
    
    //  @selftest
    //  Start a server to test against, and bind to endpoint
    zsys_dir_create (".hydra_test");
    zsys_dir_change (".hydra_test");
    zactor_t *server = zactor_new (hydra_server, "hydra_client_test");
    if (verbose)
        zstr_send (server, "VERBOSE");
    zstr_sendx (server, "LOAD", "hydra.cfg", NULL);
    zstr_sendx (server, "BIND", "ipc://@/hydra", NULL);
    
    hydra_client_verbose = verbose;
    hydra_client_t *client = hydra_client_new ("ipc://@/hydra", 500);
    int rc = hydra_client_fetch (client, HYDRA_PROTO_FETCH_RESET);
    assert (rc == -1);
    hydra_client_destroy (&client);
    
    zactor_destroy (&server);
    
    //  Delete the test directory
    zsys_dir_change ("..");
    zdir_t *dir = zdir_new (".hydra_test", NULL);
    assert (dir);
    zdir_remove (dir, true);
    zdir_destroy (&dir);
    //  @end
    printf ("OK\n");
}
