The following ABNF grammar defines the The Hydra Protocol:

    hydra = hello *( tags / tag / post ) [ goodbye ]
    hello = c:hello ( s:hello-ok / s:invalid / s:failed )
    get-post = c:get-post ( s:get-post-ok / s:invalid / s:failed )
    get-tags = c:get-tags ( s:get-tags-ok / s:invalid / s:failed )
    get-tag = c:get-tag ( s:get-tag-ok / s:invalid / s:failed )
    goodbye = c:goodbye ( s:goodbye-ok / s:invalid / s:failed )

    ;  Open new connection                                                   

    HELLO           = signature %d1 address
    signature       = %xAA %xA0             ; two octets
    address         = string                ; Client address

    ;  Accept new connection and return most recent (last) post.             

    HELLO-OK        = signature %d2 post-id
    post-id         = string                ; Post identifier

    ;  Fetch a given post's content                                          

    GET-POST        = signature %d3 post-id
    post-id         = string                ; Post identifier

    ;  Return a post's metadata and content                                  

    GET-POST-OK     = signature %d4 post-id reply-to previous tags timestamp digest type content
    post-id         = string                ; Post identifier
    reply-to        = string                ; Parent post, if any
    previous        = string                ; Previous post, if any
    tags            = strings               ; Content tags
    timestamp       = string                ; Content date/time
    digest          = 20OCTET               ; SHA1 content digest
    type            = string                ; Content type
    content         = msg                   ; Content body

    ;  Request list of tags known by peer                                    

    GET-TAGS        = signature %d5

    ;  Return list of known tags                                             

    GET-TAGS-OK     = signature %d6 tags
    tags            = strings               ; List of known tags

    ;  Request summary for a given tag                                       

    GET-TAG         = signature %d7 tag
    tag             = string                ; Name of tag

    ;  Return latest post ID for given tag                                   

    GET-TAG-OK      = signature %d8 tag post-id
    tag             = string                ; Name of tag
    post-id         = string                ; Post identifier

    ;  Close the connection politely                                         

    GOODBYE         = signature %d9

    ;  Handshake a connection close                                          

    GOODBYE-OK      = signature %d10

    ;  Command was invalid at this time                                      

    INVALID         = signature %d11

    ;  Command failed for some specific reason                               

    FAILED          = signature %d12 reason
    reason          = string                ; Reason for failure

    ; A list of string values
    strings         = strings-count *strings-value
    strings-count   = number-4
    strings-value   = longstr

    ; A msg is zero or more distinct frames
    msg             = *frame

    ; Strings are always length + text contents
    string          = number-1 *VCHAR
    longstr         = number-4 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-4        = 4OCTET
