The following ABNF grammar defines the The Hydra Protocol:

    hydra = hello *( tags / tag / post ) [ goodbye ]
    hello = c:hello ( s:hello-ok / s:invalid / s:failed )
    get-post = c:get-post ( s:get-post-ok / s:invalid / s:failed )
    get-tags = c:get-tags ( s:get-tags-ok / s:invalid / s:failed )
    get-tag = c:get-tag ( s:get-tag-ok / s:invalid / s:failed )
    goodbye = c:goodbye ( s:goodbye-ok / s:invalid / s:failed )

    ;  Open new connection                                                   

    HELLO           = signature %d1 identity nickname
    signature       = %xAA %xA0             ; two octets
    identity        = string                ; Client identity
    nickname        = string                ; Client nickname

    ;  Accept new connection and return most recent post, if any.            

    HELLO-OK        = signature %d2 post-id identity nickname
    post-id         = string                ; Post identifier
    identity        = string                ; Server identity
    nickname        = string                ; Server nickname

    ;  Fetch a given post's content                                          

    GET-POST        = signature %d3 post-id
    post-id         = string                ; Post identifier

    ;  Return a post's metadata and content                                  

    GET-POST-OK     = signature %d4 post-id reply-to previous tags timestamp digest type content
    post-id         = string                ; Post identifier
    reply-to        = string                ; Parent post, if any
    previous        = string                ; Previous post, if any
    tags            = string                ; Content tags, space delimited
    timestamp       = string                ; Content date/time
    digest          = string                ; Content digest
    type            = string                ; Content type
    content         = chunk                 ; Content body

    ;  Request list of all tags known by peer                                

    GET-TAGS        = signature %d5

    ;  Return list of known tags                                             

    GET-TAGS-OK     = signature %d6 tags
    tags            = string                ; Known tags, space delimited

    ;  Request summary for a given tag                                       

    GET-TAG         = signature %d7 tag
    tag             = string                ; Name of tag

    ;  Return latest post ID for given tag                                   

    GET-TAG-OK      = signature %d8 tag post-id
    tag             = string                ; Name of tag
    post-id         = string                ; Post identifier

    ;  Close the connection politely                                         

    GOODBYE         = signature %d9

    ;  Handshake a connection close                                          

    GOODBYE-OK      = signature %d10

    ;  Command failed for some specific reason                               

    ERROR           = signature %d11 status reason
    status          = number-2              ; 3-digit status code
    reason          = string                ; Printable explanation

    ; A chunk has 4-octet length + binary contents
    chunk           = number-4 *OCTET

    ; Strings are always length + text contents
    string          = number-1 *VCHAR

    ; Numbers are unsigned integers in network byte order
    number-1        = 1OCTET
    number-2        = 2OCTET
    number-4        = 4OCTET
