/*  =========================================================================
    hydra_client - Hydra Client

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of zbroker, the ZeroMQ broker project.           
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

/*
@header
    This is a client for the Hydra protocol that connects, synchronizes,
    and then terminates. It's not a general client API.
@discuss
    Generated by zproto and implements a background actor that manages the
    connection to the Hydra server.
@end
*/

#include "hydra_classes.h"

//  Forward reference to method arguments structure
typedef struct _client_args_t client_args_t;

//  This structure defines the context for a client connection
typedef struct {
    //  These properties must always be present in the client_t
    //  and are set by the generated engine. The cmdpipe gets
    //  messages sent to the actor; the msgpipe may be used for
    //  faster asynchronous message flows.
    zsock_t *cmdpipe;           //  Command pipe to/from caller API
    zsock_t *msgpipe;           //  Message pipe to/from caller API
    zsock_t *dealer;            //  Socket to talk to server
    hydra_msg_t *message;       //  Message from and to server
    client_args_t *args;        //  Arguments from methods
} client_t;

//  Include the generated client engine
#include "hydra_client_engine.inc"

//  Allocate properties and structures for a new client instance.
//  Return 0 if OK, -1 if failed

static int
client_initialize (client_t *self)
{
    return 0;
}

//  Free properties and structures for a client instance

static void
client_terminate (client_t *self)
{
    //  Destroy properties here
}




//  ---------------------------------------------------------------------------
//  set_client_address
//

static void
set_client_address (client_t *self)
{

}


//  ---------------------------------------------------------------------------
//  use_connect_timeout
//

static void
use_connect_timeout (client_t *self)
{
    engine_set_timeout (self, self->args->timeout);
}


//  ---------------------------------------------------------------------------
//  connect_to_server_endpoint
//

static void
connect_to_server_endpoint (client_t *self)
{
    if (zsock_connect (self->dealer, "%s", self->args->endpoint)) {
        engine_set_exception (self, bad_endpoint_event);
        zsys_warning ("could not connect to %s", self->args->endpoint);
    }
}


//  ---------------------------------------------------------------------------
//  use_response_timeout
//

static void
use_response_timeout (client_t *self)
{

}


//  ---------------------------------------------------------------------------
//  prepare_to_get_last_post
//

static void
prepare_to_get_last_post (client_t *self)
{
    engine_set_exception (self, have_post_event);
}


//  ---------------------------------------------------------------------------
//  store_the_post
//

static void
store_the_post (client_t *self)
{

}


//  ---------------------------------------------------------------------------
//  prepare_to_get_previous_post
//

static void
prepare_to_get_previous_post (client_t *self)
{

}


//  ---------------------------------------------------------------------------
//  signal_success
//

static void
signal_success (client_t *self)
{
    zsock_send (self->cmdpipe, "si", "SUCCESS", 0);
}


//  ---------------------------------------------------------------------------
//  signal_incomplete
//

static void
signal_incomplete (client_t *self)
{
    zsock_send (self->cmdpipe, "sis", "FAILURE", -1, "Premature disconnection");
}


//  ---------------------------------------------------------------------------
//  signal_bad_endpoint
//

static void
signal_bad_endpoint (client_t *self)
{
    zsock_send (self->cmdpipe, "sis", "FAILURE", -1, "Bad server endpoint");
}


//  ---------------------------------------------------------------------------
//  signal_server_not_present
//

static void
signal_server_not_present (client_t *self)
{
    zsock_send (self->cmdpipe, "sis", "FAILURE", -1, "Server is not reachable");
}


//  ---------------------------------------------------------------------------
//  signal_internal_error
//

static void
signal_internal_error (client_t *self)
{
    zsock_send (self->cmdpipe, "sis", "FAILURE", -1, "Internal server error");
}


//  ---------------------------------------------------------------------------
//  Selftest

void
hydra_client_test (bool verbose)
{
    printf (" * hydra_client: ");
    if (verbose)
        printf ("\n");
    
    //  @selftest
    //  Start a server to test against, and bind to endpoint
    zactor_t *server = zactor_new (hydra_server, "hydra_client_test");
    if (verbose)
        zstr_send (server, "VERBOSE");
    zstr_sendx (server, "BIND", "ipc://@/hydra", NULL);
    
    hydra_client_t *client = hydra_client_new ("ipc://@/hydra", 500);
    if (verbose)
        hydra_client_verbose (client);
    hydra_client_destroy (&client);
    
    zactor_destroy (&server);
    //  @end
    printf ("OK\n");
}
