#! /bin/bash
#
#   Regenerates models, needs imatix/gsl and zeromq/zproto

gsl -quiet -trace:1 -script:zproto_codec_c.gsl hydra_msg.xml
gsl -quiet -script:zproto_codec_java.gsl hydra_msg.xml
gsl -quiet hydra_client.xml
gsl -quiet hydra_server.xml

MAIN=hydrad

gcc -g -o $MAIN \
    $MAIN.c \
    hydra_msg.c hydra_client.c hydra_server.c \
    -lczmq -lzmq
test $? -ne 0 && exit

